trigger:
- master

variables:
  buildConfiguration: 'Release'

jobs:
  - job: Build_Test_Publish
    displayName: 'Build, test and publish to NuGet'
    pool:
        vmImage: 'windows-latest'

    steps:
    - task: UseDotNet@2
      displayName: Install .NET Core SDK
      inputs:
        packageType: 'sdk'
        version: 3.x

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: 'JsonEnvelopes.sln'
        arguments: --configuration $(buildConfiguration)

    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: '**/JsonEnvelopes.Tests.csproj'
        arguments: '--configuration $(buildConfiguration) --no-restore --no-build -- xunit.parallelizeAssembly=true xunit.parallelizeTestCollections=true'

    - task: NuGetToolInstaller@1
      displayName: 'Install nuget'  
      inputs:
        versionSpec: '*'
        checkLatest: true

    - script: nuget pack "$(Build.SourcesDirectory)\JsonEnvelopes.nuspec"
      displayName: nuget pack

    - script: nuget push $(System.ArtifactsDirectory)/**/JsonEnvelopes.*.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey $(GitHub-ApiKey)
      displayName: 'nuget push -> nuget.org'
