trigger:
- main

variables:
  buildConfiguration: 'Release'
  isMainBranch: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  
jobs:
  - job: Build_Test_Publish
    displayName: 'Windows: build, test and publish to nuget.org'
    pool:
        vmImage: 'windows-latest'

    steps:
    - task: UseDotNet@2
      displayName: Install .NET 6 SDK
      inputs:
        packageType: 'sdk'
        version: 6.x

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: 'JsonEnvelopes.sln'
        arguments: --configuration $(buildConfiguration)

    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: '**/JsonEnvelopes.Tests.csproj'
        arguments: '--configuration $(buildConfiguration) --no-restore --no-build -- xunit.parallelizeAssembly=true xunit.parallelizeTestCollections=true'

    - task: NuGetToolInstaller@1
      displayName: 'Install nuget'  
      inputs:
        versionSpec: '*'
        checkLatest: true

    - script: nuget pack "$(Build.SourcesDirectory)\JsonEnvelopes.nuspec"
      displayName: nuget pack

    - script: nuget push "$(Build.SourcesDirectory)\JsonEnvelopes.*.nupkg" -Source https://api.nuget.org/v3/index.json -ApiKey $(NuGet-ApiKey)
      displayName: 'nuget push -> nuget.org'
      condition: and(succeeded(), eq(variables.isMainBranch, 'True'))